- name: Configuring mysql server
  hosts: mysql
  become: yes # Remote server (mysql server)
  vars_files:
  - /var/expense/credentials_mysql.yaml # this is there in the ansible server
  roles:
  - mysql
